

using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MK.IO.Models
{

    /// <summary>
    /// 
    /// </summary>

    public class StreamingEndpointProperties
    {
        /// <summary>
        /// Gets or Sets AccessControl
        /// </summary>
        public StreamingEndpointAccessControl AccessControl { get; set; }

        /// <summary>
        /// If CDN is enabled, the path that must be inserted after the hostname and before the locator, e.g. https://<hostName>/<cdnBasePath>/<locator>.
        /// </summary>
        /// <value>If CDN is enabled, the path that must be inserted after the hostname and before the locator, e.g. https://<hostName>/<cdnBasePath>/<locator>.</value>
        [JsonInclude]
        public string CdnBasePath { get; private set; }

        /// <summary>
        /// Indicates if CDN is enabled for the streaming endpoint.
        /// </summary>
        /// <value>Indicates if CDN is enabled for the streaming endpoint.</value>
        public bool? CdnEnabled { get; set; }

        /// <summary>
        /// If CDN is enabled, the optional CDN profile name for the streaming endpoint.
        /// </summary>
        /// <value>If CDN is enabled, the optional CDN profile name for the streaming endpoint.</value>
        public string CdnProfile { get; set; }

        /// <summary>
        /// If CDN is enabled, the CDN provider name for the streaming endpoint.
        /// </summary>
        /// <value>If CDN is enabled, the CDN provider name for the streaming endpoint.</value>
        public StreamingEndpointCdnProvider? CdnProvider { get; set; }

        /// <summary>
        /// The creation date and time of the streaming endpoint. Set by the system.
        /// </summary>
        /// <value>The creation date and time of the streaming endpoint. Set by the system.</value>
        [JsonInclude]
        public DateTime? Created { get; private set; }

        /// <summary>
        /// Gets or Sets CrossSiteAccessPolicies
        /// </summary>
        public CrossSiteAccessPolicies CrossSiteAccessPolicies { get; set; }

        /// <summary>
        /// NOT SUPPORTED pending implementation of DNS validation.          Custom host names for the streaming endpoint. Must be unique within the region.          If not specified, a default hostname will be used. The best practice for custom DNS         is to use a CNAME pointing to the autogenerated hostname derived from the streaming endpoint name,         and to configure your CDN to deliver a HOST header to the origin server for routing purposes.
        /// </summary>
        /// <value>NOT SUPPORTED pending implementation of DNS validation.          Custom host names for the streaming endpoint. Must be unique within the region.          If not specified, a default hostname will be used. The best practice for custom DNS         is to use a CNAME pointing to the autogenerated hostname derived from the streaming endpoint name,         and to configure your CDN to deliver a HOST header to the origin server for routing purposes.</value>
        [Obsolete] public List<string> CustomHostNames { get; set; }

        /// <summary>
        /// The description of the streaming endpoint.
        /// </summary>
        /// <value>The description of the streaming endpoint.</value>
        public string Description { get; set; }

        /// <summary>
        /// The fqdn of the streaming endpoint. This is the output hostname and is always configured. To set a custom hostname, use the customHostNames property.
        /// </summary>
        /// <value>The fqdn of the streaming endpoint. This is the output hostname and is always configured. To set a custom hostname, use the customHostNames property.</value>
        [JsonInclude]
        public string HostName { get; private set; }

        /// <summary>
        /// The last modified date and time of the streaming endpoint. Set by the system.
        /// </summary>
        /// <value>The last modified date and time of the streaming endpoint. Set by the system.</value>
        [JsonInclude]
        public DateTime? LastModified { get; private set; }

        /// <summary>
        /// The maximum amount of time that content will be cached, in seconds. This value is superceded by any ETAG values set by the infrastructure.
        /// </summary>
        /// <value>The maximum amount of time that content will be cached, in seconds. This value is superceded by any ETAG values set by the infrastructure.</value>
        public int? MaxCacheAge { get; set; }

        /// <summary>
        /// The provisioning state of the streaming endpoint. Set by the system. One of InProgress,Succeeded,Failed.
        /// </summary>
        /// <value>The provisioning state of the streaming endpoint. Set by the system. One of InProgress,Succeeded,Failed.</value>
        [JsonInclude]
        public StreamingEndpointProvisioningState? ProvisioningState { get; private set; }

        /// <summary>
        /// The runtime state of the streaming endpoint. Set by the system. One of Running,Stopped,Deleted,Creating,Starting,Stopping,Deleting,Scaling.
        /// </summary>
        /// <value>The runtime state of the streaming endpoint. Set by the system. One of Running,Stopped,Deleted,Creating,Starting,Stopping,Deleting,Scaling.</value>
        [JsonInclude]
        public StreamingEndpointResourceState? ResourceState { get; private set; }

        /// <summary>
        /// The number of scale units for the streaming endpoint. This will determine your minimum scale. A value of 0 will result in the streaming endpoints using a Standard SKU.  A value greater than zero indicates that the 'Premium' SKUs will be provisioned.
        /// </summary>
        /// <value>The number of scale units for the streaming endpoint. This will determine your minimum scale. A value of 0 will result in the streaming endpoints using a Standard SKU.  A value greater than zero indicates that the 'Premium' SKUs will be provisioned.</value>
        public int? ScaleUnits { get; set; }

        /// <summary>
        /// Gets or Sets Sku
        /// </summary>
        public StreamingEndpointsCurrentSku Sku { get; set; }


        /// <summary>
        /// Get the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StreamingEndpointProperties {\n");
            sb.Append("  AccessControl: ").Append(AccessControl).Append("\n");
            sb.Append("  CdnEnabled: ").Append(CdnEnabled).Append("\n");
            sb.Append("  CdnProfile: ").Append(CdnProfile).Append("\n");
            sb.Append("  CdnProvider: ").Append(CdnProvider).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  CrossSiteAccessPolicies: ").Append(CrossSiteAccessPolicies).Append("\n");
            sb.Append("  CustomHostNames: ").Append(CustomHostNames).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  HostName: ").Append(HostName).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  MaxCacheAge: ").Append(MaxCacheAge).Append("\n");
            sb.Append("  ProvisioningState: ").Append(ProvisioningState).Append("\n");
            sb.Append("  ResourceState: ").Append(ResourceState).Append("\n");
            sb.Append("  ScaleUnits: ").Append(ScaleUnits).Append("\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Get the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this, ConverterLE.Settings);
        }

    }
}
